config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#home'
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: :create
    resources :reviews, only: :create
    member do
      get :search
    end
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: %i[list] }
  validates :list, uniqueness: { scope: %i[movie] }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :content, :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[search show]

  def home
  end

  def search
    if params[:query] == ""
      redirect_to list_path(params[:id])
    else
      @movies = @list.movies.where(title: params[:query])
      @query = params[:query]
    end
  end

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @review = Review.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    @review.save
    redirect_to list_path(@list)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
      <%= link_to root_path, class: "navbar-home" do %>
          <i class="fas fa-home"></i>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "My Lists", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New List", new_list_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
      <%= yield %>
  </body>
</html>

app/views/lists/home.html.erb
<div class="banner text-center">
  <div>
    <h1>
      <span id="banner-typed-text"></span>
    </h1>
    <%= link_to "All My Lists", lists_path, class: "btn btn-ghost-home m-4"  %>
  </div>
</div>
<div class="footer fixed-bottom">
  <div class="footer-links">
    <a href="https://github.com/houzyk" target="_blank"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> at Le Wagon Mauritius
  </div>
</div>

app/views/lists/index.html.erb
<div class="container">
  <div class="cards">
      <% @lists.each do |list|%>
          <div class="card-category" data-aos="fade-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
            <%= link_to "#{list.name}", list_path(list), class:"btn btn-ghost-card"%>
          </div>
      <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h5 class="text-center my-3">Add A New List of Movies</h5>
      <%= simple_form_for(@list) do |f| %>
        <%= f.input :name, label:false, placeholder: "New List Name"%>
        <div class="text-center">
          <%= f.submit class: "btn btn-ghost"%> <br>
          <%= link_to "Cancel", lists_path, class: "btn btn-ghost-danger mt-3"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/search.html.erb
<div class="container">
  <div class="text-center">
    <p>You searched For <b><%= @query%></b>. Here are the movie(s) relating to your search.</p>
  </div>
  <div class="cards">
  <% @movies.each do |movie|%>
      <div class="card-trip">
        <img src=<%= movie.poster_url%> />
            <div class="card-trip-infos">
              <div>
              <h2><%= movie.title%></h2>
              <p class="my-3"><%= movie.overview%></p>
            </div>
            <h2 class="card-trip-pricing"><%= movie.rating%></h2>
          </div>
      </div>
    <% end %>

app/views/lists/show.html.erb
<div class="container">
  <div class="row show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    <div class="col-12 col-md-6 d-flex justify-content-center align-items-center">
      <h1 class="ghost-title"> <%= @list.name%> </h1>
    </div>
    <div class="col-12 col-md-6 p-4 d-flex justify-content-center align-items-center show-banner-side">
    <div class="form-group">
      <%= simple_form_for([@list, @bookmark]) do |f| %>
        <%= f.input :comment, class:"form-control w-10", label: false, placeholder: "Add A Bookmark CommenT"%>
        <%= f.association :movie, input_html: { class: 'select2' }, class:"form-control",  label: false, placeholder: "Choose A Movie"%>
        <%= f.button :submit, class:"btn btn-primary" %>
      <% end %>
    </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="cards">
  <% @list.bookmarks.each do |bookmark|%>
      <div class="card-trip">
        <img src=<%= bookmark.movie.poster_url%> />
            <div class="card-trip-infos">
              <div>
              <h2><%= bookmark.movie.title%></h2>
              <p class="my-3"><%= bookmark.movie.overview%></p>
              <h6>"<%= bookmark.comment%>"</h6>
              <%= link_to "",
                  bookmark_path(bookmark),
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  class:"fas fa-trash card-delete"
                %>
            </div>
            <h2 class="card-trip-pricing"><%= bookmark.movie.rating%></h2>
          </div>
      </div>
    <% end %>


    <div>
    <%= simple_form_for([@list, @review]) do |f| %>
      <%= f.input :content, label: false, placeholder: "Add A Review to the '#{@list.name}'' list..." %>
      <%= f.input :rating, label: false, collection: (0..5).to_a%>
      <%= f.button :submit, class:"btn btn-ghost btn-block mb-3"%>
    <% end %>
    <% @list.reviews.first(4).each do |review|%>
        <div class="notification">
          <img src='https://kitt.lewagon.com/placeholder/users/arthur-littm' class="avatar-large" />
          <div class="notification-content">
            <p><small><%= review.rating%></small></p>
            <p><%= review.content%></p>
          </div>
        </div>
      <%end%>
    </div>

  </div>
</div>

<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/houzyk" target="_blank"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    <div>
      <%= form_tag search_list_path, method: :get do %>
      <div class="search-form-control form-inline">
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          id:"search_query",
          placeholder: "Find a movie in '#{@list.name}'"
        %>
        <%= submit_tag "Search", class: "btn btn-info" %>
      </div>
      <% end %>
  </div>
  </div>
</div>